spring:
  application:
    name: admin-consumer-ribbon
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8883
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/