spring:
  application:
    name: admin-consumer-feign
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8884
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
feign:
  hystrix:
    enabled: true
