eureka:
  client:
    serviceUrl:
      defaultZone: http://mww-eureka:8880/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8891
server:
  port: 8881
spring:
 application:
  name: admin-service
 zipkin:
  base-url: http://localhost:9411
