spring:
  application:
    name: mww-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true
server:
  port: 8885
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

